#! Licensed to the Apache Software Foundation (ASF) under one or more
#! contributor license agreements.  See the NOTICE file distributed with
#! this work for additional information regarding copyright ownership.
#! The ASF licenses this file to You under the Apache License, Version 2.0
#! (the "License"); you may not use this file except in compliance with
#! the License.  You may obtain a copy of the License at
#!
#!      http://www.apache.org/licenses/LICENSE-2.0
#!
#! Unless required by applicable law or agreed to in writing, software
#! distributed under the License is distributed on an "AS IS" BASIS,
#! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#! See the License for the specific language governing permissions and
#! limitations under the License.

#@ load("templates.lib.yml",
#@      "project_gcr_image_resource",
#@      "bash_task",
#@ )
#@ load("templates.lib.txt",
#@      "dump_previous_abi_bash_task",
#@      "dump_current_abi_bash_task",
#@      "diff_abi_bash_task",
#@ )
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
resources:
  #@overlay/append
  - #@ project_gcr_image_resource("abigail-tools-image", "geode-native-abigail-tools")

jobs:
  #@overlay/append
  - name: abi-check
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: abigail-tools-image
            - get: source
              trigger: true
            - get: geode
            - get: geode-native
      - in_parallel:
          fail_fast: true
          steps:
            - #@ bash_task("dump-previous-abi", [{"name":"geode-native", "path":"source"}, {"name":"geode"}], [{"name":"previous-abi", "path":"abi"}], dump_previous_abi_bash_task(), "abigail-tools-image", caches=[{"path":"abi"}])
            - #@ bash_task("dump-current-abi", [{"name":"source"}, {"name":"geode"}], [{"name":"current-abi", "path":"abi"}], dump_current_abi_bash_task(), "abigail-tools-image", caches=[{"path":"abi"}])
      - #@ bash_task("diff-abi", [{"name":"previous-abi"}, {"name":"current-abi"}], [], diff_abi_bash_task(), "abigail-tools-image")

groups:
  #@overlay/match by="name", missing_ok=True
  - name: all
    jobs:
      #@overlay/append
      - abi-check

  #@overlay/match by="name", missing_ok=True
  - name: build
    jobs:
      #@overlay/append
      - abi-check
